name: pokedex_scaffold
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: 9.2.2
  flutter_screenutil: 5.9.3
  flutter_svg: 2.0.10+1
  intl: 0.19.0
  responsive_builder: 0.7.1
  fancy_bottom_tab_bar:    
    git:
      url: https://github.com/kitcarson88/flutter-fancy-bottom-tab-bar.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  auto_route_generator: 9.0.0
  build_runner: 2.4.12
  flutter_gen_runner: 5.7.0

flutter_gen:
  output: lib/ui/styles # Optional (default: lib/gen/)
  line_length: 100 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
  assets:
    enabled: true
    class_name: Assets
  fonts:
    enabled: true
    outputs:
      class_name: FontFamily
  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors

flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/lato/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic

  generate: true

  uses-material-design: true

  assets:
    - assets/icons/
    # - assets/images/
