name: pokedex_scaffold
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: 9.2.2
  bloc: 8.1.4
  cached_network_image: 3.4.1
  collection: 1.18.0
  connectivity_plus: 6.0.5
  dio: 5.7.0
  dio_smart_retry: 6.0.0
  flutter_bloc: 8.1.6
  flutter_flavorizr: 2.2.3
  flutter_hooks: 0.20.5
  flutter_platform_widgets: 7.0.1
  flutter_screenutil: 5.9.3
  flutter_svg: 2.0.10+1
  freezed_annotation: 2.4.4
  get_it: 7.7.0
  hooked_bloc: 1.5.0
  injectable: 2.4.4
  internet_connection_checker: 1.0.0+1
  intl: 0.19.0
  json_annotation: 4.9.0
  loader_overlay: 4.0.2+1
  logging: 1.2.0
  responsive_builder: 0.7.1
  retrofit: 4.4.1
  skeletonizer: 1.4.2
  curl_logger_dio_interceptor:
    path: libraries/curl_logger_dio_interceptor
  fancy_bottom_tab_bar:    
    git:
      url: https://github.com/kitcarson88/flutter-fancy-bottom-tab-bar.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  auto_route_generator: 9.0.0
  build_runner: 2.4.12
  flutter_gen_runner: 5.7.0
  freezed: 2.5.7
  injectable_generator: 2.6.2
  json_serializable: 6.8.0
  retrofit_generator: 9.1.2

flutter_gen:
  output: lib/ui/styles # Optional (default: lib/gen/)
  line_length: 100 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
  assets:
    enabled: true
    class_name: Assets
  fonts:
    enabled: true
    outputs:
      class_name: FontFamily
  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors

flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/lato/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic

  generate: true

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavors"
  flavors:
    dev:
      app:
        name: "[D] Pokedex Scaffold"
      android:
        applicationId: "it.kitcarson88.pokedexscaffold_dev"
        icon: "assets/launcher_icons/ic_launcher_dev.png"
      ios:
        bundleId: "it.kitcarson88.pokedexscaffold-dev"
        buildSettings:
          # DEVELOPMENT_TEAM: XXXXXXXXXX
        icon: "assets/launcher_icons/ic_launcher_dev.png"
    devh:
      app:
        name: "[D] Pokedex Scaffold"
      android:
        applicationId: "it.kitcarson88.pokedexscaffold_dev"
        icon: "assets/launcher_icons/ic_launcher_dev.png"
    qa:
      app:
        name: "[T] Pokedex Scaffold"
      android:
        applicationId: "it.kitcarson88.pokedexscaffold_test"
        icon: "assets/launcher_icons/ic_launcher_qa.png"
      ios:
        bundleId: "it.kitcarson88.pokedexscaffold-test"
        buildSettings:
          # DEVELOPMENT_TEAM: XXXXXXXXXX
        icon: "assets/launcher_icons/ic_launcher_qa.png"
    qah:
      app:
        name: "[T] Pokedex Scaffold"
      android:
        applicationId: "it.kitcarson88.pokedexscaffold_test"
        icon: "assets/launcher_icons/ic_launcher_qa.png"
    prod:
      app:
        name: "Pokedex Scaffold"
      android:
        applicationId: "it.kitcarson88.pokedexscaffold"
        icon: "assets/launcher_icons/ic_launcher.png"
      ios:
        bundleId: "it.kitcarson88.pokedexscaffold"
        buildSettings:
          # DEVELOPMENT_TEAM: XXXXXXXXXX
        icon: "assets/launcher_icons/ic_launcher.png"
    prodh:
      app:
        name: "Pokedex Scaffold"
      android:
        applicationId: "it.kitcarson88.pokedexscaffold"
        icon: "assets/launcher_icons/ic_launcher.png"