name: curl_logger_dio_interceptor
description: Get your http requests printed as curl command in your terminal. Share them easily with your colleagues and import them in Postman!
version: 0.0.4
homepage: https://github.com/OwnWeb/curl_logger_dio_interceptor

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  dio: ^5.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
